### PR TITLE
Set up

### PR DESCRIPTION
**Pull request by sjcco**
Milestone 1: Project setup

- Set up project as listed in general requirements
- add lib folder
- add bin folder with main.rb executable

### CODE REVIEW

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: INVALID ♻️

Hello @sjcco, kindly refer to this [news](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-#) about linter errors as a reason for project invalidation.

Make sure your linters are passing before submitting another CRR.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by sjcco** [comment]
Inspecting 1 file
W

Offenses:

bin/main.rb:1:1: W: Lint/ScriptPermission: Script file main.rb doesn't have execute permission.
#!/usr/bin/env ruby
^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Carlos Campos Ojeda** 
Good job with your first submission for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
Just one last detail to improve before you can go ahead:

- [ ] All the linters checks should be successful 
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are some changes required, please check the comments below._

- ### To Highlight
  - [x] The project follows Git flow 💯
- ### To Improve
  - [x] [MANDATORY] Linters are still failing, kindly fix them. on this you need to set execute permission on remote repo, This [Tool](https://www.gitpod.io/) will help you to do that. 
  


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on @slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
@slack: Rukundo Eric**

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Required changes:full_moon:
**Hi Carlos!
Nice one:clap::clap:. The root project is well structured with the right files placed inside the right directory. But we just have a change to make to enable us to move on to the next milestone**.

**Mandatory requirement**

- [ ] naming the file to only main is allowed. Kindly fix this.

make the above-required change and when you are done, request another review.
Kindly drop your questions/comments here and ping me on slack @ Eric Enaburekhan to respond.
Happy Coding:blush:
Eric Enaburekhan

**Review by Georjane — APPROVED** [review]
## Status: PR Approved ✔️ ✔️
### Hi Team 🙌
Congratulations on successfully completing this milestone. You can go ahead and merge this PR. 👍 

Good luck on the next milestones and Happy Coding 💻

**Pull request merged**
