### PR TITLE
Milestone 2: User interface

### PR DESCRIPTION
**Pull request by sjcco**
- Display prompts for users 
- You can run your game and play with the basic flow.
- Added all steps to be able to play tic tac toe

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Required changes:full_moon:
**Hi Carlos!
Great job on this milestone. The print statement for player 1 and player 2 is really innovative. Keep up the good work:clap::clap:. However, there are a few changes we need to make to get this milestone working and approved:muscle:.**

**Mandatory requirements**

- [x] the game asks the player to select from available moves. Once a move is made, that move should no longer be available. Then the player selects from the available moves left. Kindly fix this

- [x] the game informs the player if the selected move is invalid (without computing what an invalid move is). When I entered  6 a couple of times on the same game. The game never raises an invalid move for the subsequent moves. kindy fix this.

- [x] the game informs the player if the selected move is a winning move (without computing the winning move). Currently, It does no display the Winner. Please fix this

- [x] the game informs the player if the selected move is a draw move (without computing draw). It does not also display a draw.  Fix this

- [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png)). Just one loop is needed for this milestone. every other code 
displays prompt for users (print/puts) and collects user input (`gets.chomp`).

Make the required changes and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond
Happy Coding:blush:
Eric Enaburekhan

**Review by cyonii — CHANGES_REQUESTED** [review]
## Status: Changes Required ✍️

Hello @sjcco, you have a nice project so far, you have implemented a nice mock-up for the user interface.

However, I find this very little issue with your game flow: Although the logic is not expected to work in this milestone, in the Tic-Tac-Toe game there are only 9 possible moves per game session. This means your game should declare a winner or declare the game a tie after 9 moves. NOTE: It doesn't need any logic to determine this, you can choose at random who the winner is, or if the game was a tie.

Kindly implement this change and resubmit for re-review.

### Happy coding 🤝
You can find me on [slack](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance.

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯
  - [x] It has a descriptive branch name 💯
  - [x] It has a very wonderful design 💯

- ### To Improve
  - [ ] [MANDATORY] The main.rb doesn't have a UI for these situations:
    - When a player wins and
    - when a player makes an invalid move
  - [ ] [OPTIONAL] I strongly recommend using functions to make this codebase readable and very easily manageable

- ### Note
  - Remember, the logic doesn't need to work.   


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on @slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
@slack: Rukundo Eric**

**Review by smcommits — CHANGES_REQUESTED** [review]
# Status: Changes Required
Hello! @sjcco
You have done a great job so far but we still need to fix a few things before you can move on to next milestone. 

# Required Changes

- [x] **Please make sure you only add the code related to user interaction in your main.rb** 
- [x] **You should only use gets and puts in your main.rb file.**

## More Details
I can see that you have implemented different methods to take of everything related to user interaction. But, they are in the wrong place. The requirements from the pathwright suggest that main.rb file should be responsible for user interaction. In this milestone you should only create content in this file. You have placed all of your methods in lib/display.rb.  ( please refer to the image below )

main_rb

Please implement all the changes and submit another code review request from your dashboard. 

#
If you need any help or further clarification. Please don't hesitate to contact me on [slack](https://microverse-students.slack.com/team/U017N7LLZ40)

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1:
Hello, @sjcco.

**Great job! I can see that you have implemented all the required changes. 
This PR has been approved. You can go ahead and merge the branch. Congratulations and good luck with the next milestone.** 

# 
Any further questions? Please reach out to me on [slack](https://microverse-students.slack.com/team/U017N7LLZ40)

**Pull request merged**
